### ISSUE TITLE
Underlying dependencies not async?

### ISSUE THREAD

**Issue by patbaker82** [ryanfitz/hapi-auth-jwt#16]
Do you think its cause for concern that the underlying implementation of node-jsonwebtoken is not built in an async manner?  I'm not sure if this would impact performance or not, but if there is a high demand for signing and decrypting...

I just wanted to get your thoughts.

With regards,

Patrick

**Comment by expl0r3r** [comment]
I think this issue can now be closed since the issue that @patbaker82 has referred to has already been merged into the node-jsonwebtoken library.

**Comment by patbaker82** [comment]
@expl0r3r That pull request actually didn't implement what I was discussing.
