### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by edimoldovan** [ryanfitz/hapi-auth-jwt#17]
Hi, maybe it’s me, but I cannot make the example work. What is the purpose of this line? What should I put instead of the require('../index’) ?

server.register(require('../index'), function (error) {...

Thx!

**Comment by EdHubbell** [comment]
@edimoldovan - I just cloned and tried on my pc - Here's what I found:

1) Delete the "hapi-auth-jwt": "0.2.x", line out of hapi-auth-jwt/example/package.json - It is self referencey and seems to prevent npm install from installing hapi.

2) Make sure you run npm install in both the example and main folders.  

After that, node index.js lets me go to a browser and go to http://localhost:8080/noTokenRequired and get results.

**Comment by edimoldovan** [comment]
That worked, I missed the self reference. Thanks!
Now I only need to figure out what to pass a first param to server.register in my case.

**Comment by EdHubbell** [comment]
Aaah...  You probably just want 
``` javascript
server.register(
    {register: require('hapi-auth-jwt8')}, 
    function (err) {
```
I'm using 
``` javascript
server.register(
    {register: require('./hapi-auth-jwt8')}, 
    function (err) {
```
But that's because I have a custom build running here.  I renamed this project's index.js to hapi-auth-jwt8.js and it sits in my root folder.

**Comment by edimoldovan** [comment]
That works like a charm, again. I’d be happy to buy you a few beers, or something similar, you helped a lot. Is there any “send beer[something else]” button here? :)

**Comment by EdHubbell** [comment]
Happy to help!  I'm just avoiding doing a power point presentation today.  This is as much code as I'll get to see.  And I'm usually the one doing the asking, so happy I had some answers for someone else.

**Comment by ryanfitz** [comment]
Hey guys, the readme / example recently got updated and looks like there now a bad typo. I'll get the readme updated shortly to fix the confusion

**Comment by ryanfitz** [comment]
The example and readme have both been update. Hopefully things are a bit more clear now, let me know if you're still running into issues.

**Comment by edimoldovan** [comment]
Seams ok, thanks!
