### ISSUE TITLE
Access to raw token in validateFunc

### ISSUE THREAD

**Issue by gansbrest** [ryanfitz/hapi-auth-jwt#23]
What if I need to perform additional checks against raw token during validate? At the moment we have only decodedToken, but if I need to check if that key exists in the Redis ( "blacklist" ) I can't do that because I don't have raw token..

**Comment by nelsonic** [comment]
@gansbrest to access the "*raw*" token, you would need the original **request** object to be passed into your **validateFunc**. (see: https://github.com/ryanfitz/hapi-auth-jwt/issues/24) then you could simply access the **authorization** *header* in your **validateFunc** like this:
```js
var rawtoken = request.headers.authorization;
console.log(">> Raw JWT Token" + rawtoken);
```
( Exactly the same way as this plugin gets the Token from the request headers... )

We *also* wanted to access the **request** object for other checks in the **validateFunc** of our app, so we added it: https://github.com/ideaq/hapi-auth-jwt2#documentation :+1:

**Comment by gansbrest** [comment]
@nelsonic Took me a while to figure your documentation points to anther hapi module ) It looks good, but one question - what's the diff between your module and this one? Maybe those should merge?
