### ISSUE TITLE
Validate Function should have access to request

### ISSUE THREAD

**Issue by ShujaatTariq** [ryanfitz/hapi-auth-jwt#24]
Would it not be better if the validate function has access to the request object so that other plugins can be accessed and used for validation for. e.g. checking redis for token and fetching cached info?

**Comment by mdumouchel** [comment]
Don't forget you also have these areas you can hook into http://hapijs.com/api#request-lifecycle.  Granted you might have to add stuff to this http://hapijs.com/api#route-options to define what each route should do if its not a global thing that all routes need to do.  Just giving you some other options.  

Also if the above is something that works for you could also be turned into a plugin and give a little bit more fine grained control on how each route works.

**Comment by nelsonic** [comment]
@ShujaatTariq we thought that having access to the original request in the Validate function was useful too. so we added it: https://github.com/ideaq/hapi-auth-jwt2/commit/df732c86c86c4d4af6b483abea2e202421b58885#diff-04c6e90faac2675aa89e2176d2eec7d8R125
