### ISSUE TITLE
jsonwebtoken - not found

### ISSUE THREAD

**Issue by skota** [ryanfitz/hapi-auth-jwt#31]
When i require (jsonwebtoken). ..this is thrown Error: Cannot find module 'jsonwebtoken'.
I have hapi-auth-jwt installed....this is an excertp of my package.json

 "dependencies": {
    "bcrypt": "^0.8.3",
    "boom": "^2.7.2",
    "hapi": "^8.6.1",
    "hapi-auth-basic": "^2.0.0",
    "hapi-auth-jwt": "^2.1.2",
    "hapi-auth-jwt2": "^4.4.0",
    "joi": "^6.4.3",
    "json-web-token": "^1.5.3",
    "mongoose": "~3.8",
    "mrhorse": "^1.1.0"
  }

This is the output of npm version....
{ behapi: '1.0.0',
  npm: '2.7.4',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.2',
  openssl: '1.0.1m',
  uv: '1.4.2-node1',
  v8: '3.28.73',
  zlib: '1.2.8' }

I added jwt=require('jsonwebtoken') at the top of server.js..this is my main js file.

What am i doing wrong.  This is what i am trying to accomplish.
1. set up hapi-auth-jwt in server.js
2. Upon successful login....get a token by using  jwt.sign(user, private key)..where 'user' is a mongoose model.

UPDATE:
It worked. Apparently i had the wrong jsonwebtoken module. I removed json-web-token and added jsonwebtoken and all is well.

**Comment by tushargupta2898** [comment]
PS C:\Users\tusha\Downloads\smart-home-nodejs-master\smart-home-provider> npm install
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN smart-home-app-sample@0.0.1 No repository field.

audited 1557 packages in 9.407s
found 3 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
PS C:\Users\tusha\Downloads\smart-home-nodejs-master\smart-home-provider> nvm install
nvm : The term 'nvm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name,
or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ nvm install
+ ~~~
    + CategoryInfo          : ObjectNotFound: (nvm:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\tusha\Downloads\smart-home-nodejs-master\smart-home-provider> npm install
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN smart-home-app-sample@0.0.1 No repository field.

up to date in 12.321s
PS C:\Users\tusha\Downloads\smart-home-nodejs-master\smart-home-provider> npm start

> smart-home-app-sample@0.0.1 start C:\Users\tusha\Downloads\smart-home-nodejs-master\smart-home-provider
> node index.js isLocal

internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module './jwt-key.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\tusha\Downloads\smart-home-nodejs-master\smart-home-provider\cloud\config-provider.js:27:14)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! smart-home-app-sample@0.0.1 start: `node index.js isLocal`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the smart-home-app-sample@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tusha\AppData\Roaming\npm-cache\_logs\2018-06-28T12_54_10_378Z-debug.log

help me
