### ISSUE TITLE
Validating tokens..is this the right way?

### ISSUE THREAD

**Issue by skota** [ryanfitz/hapi-auth-jwt#32]
My handler function looks like this. At the beginning of the file..i require'd 'jsonwebtoken'.  I am wondering if this approach is correct. Any advice appreciated.

//------begin--------------------
exports.secretPage = {
    handler : function(request, reply) {
        var privateKey = Config.key.privateKey;

        if(hoek.contain(request.headers, 'authorization',{once: true}) === false ) 
            reply(Boom.forbidden("authorization header missing"));

        jwt.verify(request.headers.authorization.split(" ")[1], privateKey, function(err, decoded) {
            if(decoded === undefined) return reply(Boom.forbidden("invalid Token"));
            return reply("Here is your secret page");  //All is well...
        });
    }
};
//------------END -------------

**Comment by ryanfitz** [comment]
Your verify function is duplicating the functionality of this plugin. The plugin looks at the authorization header and validates the jwt token. When the request gets handed off to your handler, the token has already been fully verified.
