### ISSUE TITLE
Add support for "jsonwebtoken" options

### ISSUE THREAD

**Issue by hazkiel** [ryanfitz/hapi-auth-jwt#34]
The current implementation has a security vulnerability: the attacker can use the 'none' algorithm and fake a token since the list of allowed algorithms is not specified ([reference article](https://www.timmclean.net/2015/03/31/jwt-algorithm-confusion.html)).
The library used internally ([jsonwebtoken](https://github.com/auth0/node-jsonwebtoken)) allows specifying the latter as an optional 3rd parameter, check [jwt.verify](https://github.com/auth0/node-jsonwebtoken#jwtverifytoken-secretorpublickey-options-callback).
So this is just a matter of exposing the functionality in the plugin's configuration.

**Comment by eventhough** [comment]
https://www.npmjs.com/package/hapi-auth-jwt2#verifyoptions-let-you-define-how-to-verify-the-tokens-optional

See the sentence that starts with: "For security reasons..."

**Comment by nelsonic** [comment]
@hazkiel in case you are still waiting for a reply on this...
https://github.com/dwyl/hapi-auth-jwt2#specify-signing-algorithm-optional-but-highly-recommended 
:+1:

**Comment by ryanfitz** [comment]
PR #42 added this functionality. I pushed out v4.0 which includes these changes.
