### ISSUE TITLE
var error in validate function

### ISSUE THREAD

**Issue by whisher** [ryanfitz/hapi-auth-jwt#35]
Hi,
sorry to bother you.
What's the purpose of var error in validate function
because afaik is always undefined.
```javascript
var validate = function (decodedToken, callback) {

    var error,
        credentials = accounts[decodedToken.accountId] || {};

    if (!credentials) {
        return callback(error, false, credentials);
    }

    return callback(error, true, credentials)
};
```

Thanks in advance.

**Comment by ryanfitz** [comment]
This was a (poor) attempt at showing that the callback signature accepts an error object as its first param. In the example the error var is always undefined.
