### ISSUE TITLE
validationFunc doesn't run

### ISSUE THREAD

**Issue by chaiyitsheng** [ryanfitz/hapi-auth-jwt#37]
i've installed the module but can't seem to get the validation function to run, does it have to be called explicitly? or the validateFunc option will run automatically as long as there is a function supplied?

I am trying to parse the token ias to expire it after a certain time period.

Thanks :)

**Comment by edwardcodes** [comment]
Hi @chaiyitsheng, if you are having trouble, checkout: [https://github.com/dwyl/hapi-auth-***jwt2***](https://github.com/dwyl/hapi-auth-jwt2) which has more detailed explanation & usage examples.

**Comment by ryanfitz** [comment]
@chaiyitsheng can you post some sample code showing that the function isn't getting called? There is a fully working [example](https://github.com/ryanfitz/hapi-auth-jwt/blob/master/example/index.js) to show how to properly setup the plugin with a validation function.

**Comment by chaiyitsheng** [comment]
Hello there,

Thanks everyone for your kind advice. I was little confused when reading the documentation but I managed to figure it out. In my code, the function was placed out of scope. Also, I thought that "validateFunc" referred to an existing function in the library. In addition, I didn't know that "validateFunc" would have to be provided by the programmer. But, thanks again
