### ISSUE TITLE
validateFunc has an incorrect function signature

### ISSUE THREAD

**Issue by virtualdom** [ryanfitz/hapi-auth-jwt#39]
The docs state that validateFunc is a function with the following signature 
```function (request, decodedToken, callback)```
As of now, the signature is actually 
```function(decodedToken, callback)```

Consider making changes in either the documentation to reflect this or making changes in `validateFunc` code.

**Comment by edwardcodes** [comment]
@virtualdom have you considered using [https://github.com/dwyl/hapi-auth-jwt**2**](https://github.com/dwyl/hapi-auth-jwt2) which has the correct function signature/documentation...?

**Comment by ryanfitz** [comment]
@virtualdom what version of the lib are you using. The latest version 3.0 has an updated validate function signature where the request is the first param. See [here](https://github.com/ryanfitz/hapi-auth-jwt/blob/master/lib/index.js#L68) for the function call.

**Comment by virtualdom** [comment]
Got it. Noticed that the example folder in the repo lists `"hapi-auth-jwt": "2.x.x"` in its package.json, and I changed the require statement in its index.js to use the version in its node_modules. It was running 2.1.2.

Thanks for the clarification!

**Comment by ryanfitz** [comment]
ok great. I missed updating that version in the example, I'll get that fixed.
