### ISSUE TITLE
npm still downloads 2.1

### ISSUE THREAD

**Issue by ahmetcetin** [ryanfitz/hapi-auth-jwt#43]
when you install through npm, it installs version 2.1 instead of 4.0. in the new version where validateFunc called, request object also passed, but in 2.1, it only passes token and callback.

**Comment by ghost** [comment]
@ahmetcetin have a look at: https://www.npmjs.com/package/hapi-auth-jwt2
(_has everything you need. with examples, documentation and tests..._)

**Comment by ryanfitz** [comment]
version 4.0 was published to npm a couple weeks ago. I just tested a default npm install and it properly installed version 4.0. Sounds like maybe you have a package.json which is forcing it to install version 2.1
