### ISSUE TITLE
Adding option to not validate jwt

### ISSUE THREAD

**Issue by kdstew** [ryanfitz/hapi-auth-jwt#44]
The use case here is the hapi server is siting behind a gateway that is validating the jwt tokens, so by the time the request makes it to the hapi server we already know the token is valid.  But we do want to access the jwt payload to use the information.  Would you be open to a PR to allow this?
What I'm thinking is if `key` in the options has the value `false` the `authenticate` function would call `jwt.decode` instead of `jwt.validate`.

**Comment by ryanfitz** [comment]
Thats not really a feature I would want to support. However, I would look at https://www.npmjs.com/package/hapi-auth-jwt2 which supports a lot of different use cases. It might already support this feature.
