### ISSUE TITLE
Trying to setup Hapi-auth-jwt as a plugin in an external JS file

### ISSUE THREAD

**Issue by jhyland87** [ryanfitz/hapi-auth-jwt#45]
I was able to get hapi-auth-jwt working just fine using the example JS code in the readme, but I would like to have the hapi-auth-jwt plugin written as an external HapiJS module.

Reading the [Creating A Plugin](http://hapijs.com/tutorials/plugins#creating-a-plugin) tutorial on the Hapi website shows how to register a plugin, and how to do the same thing as an external module, which I've been able to do with everything else I have used thus far.

It shows you setup the module registration as the `exports.register` value:

``` javascript
exports.register = function (server, options, next) { /* Plugin stuff */ }
```

But in your readme example, its quite different

``` javascript
server.register(require('hapi-auth-jwt'), function (error) {
```

I understand how to work exports in NodeJS, im just not sure how I should structure the `register` export for this case

I'm sure this is something simple, I'm just new to HapiJS, but if you can provide an example of using this module as an external plugin, that would be very helpful. 

Thanks

**Comment by jhyland87** [comment]
I can get it to work if I throw the `server.register()` inside the `register` exports object:

``` javascript
exports.register = ( server, options, next ) => {
    server.register(require('hapi-auth-jwt'), function (error) {

        server.auth.strategy('token', 'jwt', {
            key: privateKey,
            validateFunc: validate,
            verifyOptions: { algorithms: [ 'HS256' ] }  // only allow HS256 algorithm
        });
    });

    next()
}
```

But it doesn't seen right to have it setup like that... the server.register in the exports.register, but if it is, then just let me know.

Thanks

**Comment by ryanfitz** [comment]
I believe that is still the correct way to register plugins inside another plugin.

I have another hapi plugin which uses the hapi-auth-jwt plugin and this is exactly how its registered. You can see the code [here](https://github.com/ryanfitz/elasticauth-api/blob/master/lib/index.js#L14)
