### ISSUE TITLE
Destroy/Delete active/valid token

### ISSUE THREAD

**Issue by jhyland87** [ryanfitz/hapi-auth-jwt#46]
I was wondering if there was a way to destroy/delete/deactivate/whatever a JWT thats been validated and currently in use.

Im moving my application over from CodeIgniter, which allows you to keep the sessions in a database, which makes it easy to terminate account sessions if needed. I was trying to get the same effect here, by destroying the users JWT token

**Comment by ryanfitz** [comment]
The custom `validateFunc` is where you would want to put this logic. When you generate the jwt token, include a bit of data such as 'sessionId`and in the`validateFunc` query your database to see if this session is still valid.

**Comment by shivam8800** [comment]
I don't know is there any way of deactivate a jwt token when user loggedout 
since 2 months I did not get any possible way of doing it.
Can anyone help me ?
